In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [2]:
fashion_mnist = tf.keras.datasets.fashion_mnist
(train_X, train_Y), (test_X, test_Y) = fashion_mnist.load_data()

train_X = train_X / 255
test_X = test_X / 255

train_X = train_X.reshape(-1, 28, 28, 1)
test_X = test_X.reshape(-1, 28, 28, 1)

print(f"train_X의 shape은 {train_X.shape}이고 train_Y의 shape은 {train_Y.shape}이다.")
print(f"test_X의 shape은 {test_X.shape}이고 test_Y의 shape은 {test_Y.shape}이다.")

4422102/4422102 [==============================] - 0s 0us/step
train_X의 shape은 (60000, 28, 28, 1)이고 train_Y의 shape은 (60000,)이다.
test_X의 shape은 (10000, 28, 28, 1)이고 test_Y의 shape은 (10000,)이다.


### 실제로 훈련 데이터 이미지를 보강하기 위해 다량의 이미지를 생성하고 학습을 위해 훈련 데이터에 추가해 보자.

In [49]:
 image_generator = ImageDataGenerator(rotation_range=10, zoom_range=0.10, shear_range=0.50,\
                width_shift_range=0.10, height_shift_range=0.10, horizontal_flip=True, vertical_flip=False)
 
 augument_size = 100

 randidx = np.random.randint(low=train_X.shape[0], size=augument_size)
 x_augumented = train_X[randidx].copy()
 y_augumented = train_Y[randidx].copy()

print(f"x_augumented의 shape는 {x_augumented.shape}이고 y_augumented의 shape는 {y_augumented.shape}이다.")

x_augumented의 shape는 (100, 28, 28, 1)이고 y_augumented의 shape는 (100,)이다.


In [31]:
np.random.randint(low=-2, high=3, size=10)

array([ 1, -2, -1, -1, -2,  0, -2,  0,  0,  2])

In [46]:
x = np.arange(8).reshape(-1, 4)
print(x)
print()
np.random.seed(123)
y = np.random.randint(train_X.shape[0], size=10)
z = np.random.randint(low=train_X.shape[0], size=10)
w = np.random.randint(low=train_X.shape[0], high=train_X.shape[0]+100000, size=10)

print(y)
print()
print(z)
print()
print(w)

[[0 1 2 3]
 [4 5 6 7]]

[52734 15725 28030 17730 54370 15377  7763 46203 58937 23766]

[22241    96 55409 23166 53295 53321  5664 33710 55520   111]

[ 77747  95662 128861 156676  74944 143012 133521 105507  86626 132020]
